[audio]
enable_sounds = true

[bar.default]
auto_hide = true
capsule_groups = [ "data" ]
center = [ "control-center", "group:g1", "notifications" ]
end = [
    "tray",
    "network_rx",
    "network_tx",
    "cpu",
    "ram",
    "spacer_sys",
    "brightness",
    "volume",
    "bluetooth",
    "network",
    "battery",
    "session"
]
margin_edge = 0.0
margin_ends = 0.0
radius = 0
scale = 1.0499999523162842
start = [ "launcher", "workspaces", "taskbar", "media", "audio_visualizer" ]
widget_spacing = 8

    [bar.default.monitor.HDMI-A-1]
    auto_hide = false
    scale = 1.0
    thickness = 30

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "date", "clock" ]
    opacity = 1.0
    padding = 6.0

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

[config]

[dock]
auto_hide = true
background_opacity = 1.0
enabled = true
icon_size = 40
item_spacing = 0

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

    [idle.behavior.suspend]
    action = "suspend"
    enabled = true
    lock_before_suspend = true
    timeout = 900

[keybinds]
cancel = [ "Escape" ]
down = [ "Down" ]
left = [ "Left" ]
right = [ "Right" ]
up = [ "Up" ]
validate = [ "Return" ]

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 1
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    cx = 1280.0
    cy = 957.0
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    cx = 960.0
    cy = 957.0
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

[notification]
monitors = [ "HDMI-A-1" ]

[osd]
monitors = [ "HDMI-A-1" ]

[shell]
avatar_path = "/home/talodev/Pictures/profile/nanami.jpg"
clipboard_confirm_clear_history = false
password_style = "random"
polkit_agent = true
screen_time_enabled = true
telemetry_enabled = false

    [shell.panel]
    open_near_click_control_center = true

[templates]

[theme]
builtin = "Eldritch"
source = "builtin"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "ghostty", "helix", "kcolorscheme", "niri", "qt", "starship" ]

[wallpaper]
directory = "/home/talodev/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/talodev/Pictures/Wallpapers/a_flower_on_a_dark_background.png"

    [wallpaper.last]
    path = "/home/talodev/Pictures/Wallpapers/1337222.jpeg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/talodev/Pictures/Wallpapers/a_flower_on_a_dark_background.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/talodev/Pictures/Wallpapers/1337222.jpeg"

[weather]
auto_locate = true

[widget.Download]
display = "text"
show_label = false
stat = "net_rx"
type = "sysmon"

[widget.Upload]
capsule = true
display = "text"
stat = "net_tx"
type = "sysmon"

[widget.audio_visualizer]
high_color = "secondary"
show_when_idle = true

[widget.battery]
display_mode = "graphic"
hide_when_plugged = false
scale = 0.65000000000000002
show_label = false

[widget.bongocat]
script = "scripts/bongocat.lua"
type = "scripted"

[widget.brightness]
show_label = false

[widget.clock]
capsule = true
capsule_group = "data"
capsule_padding = 16.0

[widget.cpu]
display = "graph"
show_label = false

[widget.date]
capsule = true
capsule_group = "data"

[widget.launcher]
glyph = "niri"

[widget.media]
capsule = true
hide_when_no_media = true
max_length = 150.0
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.network_rx]
display = "graph"
show_label = false

[widget.network_tx]
display = "gauge"
show_label = false

[widget.ram]
display = "text"
show_label = false

[widget.space_clock]
length = 0.0
type = "spacer"

[widget.spacer]
length = 0.0

[widget.spacer_sys]
length = 16.0
type = "spacer"

[widget.sysmon]
display = "text"
stat = "net_rx"

[widget.taskbar]
capsule = true
capsule_padding = 10.0
scale = 1.05

[widget.tray]
drawer = true
pinned = [ "Arch-Update", "OpenScreen", "Shelly", "Antigravity", "Free Download Manager" ]

[widget.volume]
show_label = false
